version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinehub
      MYSQL_USER: cinehub
      MYSQL_PASSWORD: cinehubpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql-db
    restart: unless-stopped

  tomcat:
    image: tomcat:10-jdk17
    container_name: tomcat
    ports:
      - "8080:8080"
      # optional debug port, uncomment if you want to attach a remote debugger:
      # - "8000:8000"
    volumes:
      # Preferred: mount the built WAR (run `mvn package` to create target/cinehub.war)
      - ./target/cinehub.war:/usr/local/tomcat/webapps/ROOT.war:ro
      # Alternative (hot-deploy, faster iteration): mount exploded webapp folder
      # - ./target/cinehub/:/usr/local/tomcat/webapps/ROOT:rw
      # Optional: mount logs to make catalina.out available on host
      - ./logs:/usr/local/tomcat/logs
    depends_on:
      mysql-db:
        condition: service_healthy
    # If you want remote debug, add CATALINA_OPTS environment (uncomment next line)
    # environment:
    #   - CATALINA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
    restart: unless-stopped

volumes:
  mysql-data: