version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinehub
      MYSQL_USER: cinehub
      MYSQL_PASSWORD: cinehubpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql-db
    restart: unless-stopped

  tomcat:
    image: tomcat:10-jdk17
    container_name: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./target/cinehub.war:/usr/local/tomcat/webapps/ROOT.war:ro
      - ./logs:/usr/local/tomcat/logs
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      JDBC_URL: "jdbc:mysql://mysql-db:3306/cinehub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      JDBC_USERNAME: "cinehub"
      JDBC_PASSWORD: "cinehubpass"
      HIKARI_MAX_POOL_SIZE: "10"
      HIKARI_MIN_IDLE: "2"
      HIBERNATE_DDL_AUTO: "update"
    restart: unless-stopped

volumes:
  mysql-data: